//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiLearn_JeffreyOdogba.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Enrolleds = new HashSet<Enrolled>();
        }
    
        public int CourseId { get; set; }

        [Display(Name = "Title")]
        public string title { get; set; }

        [Display(Name = "Subject")]
        public string subject { get; set; }

        [Display(Name = "Duration")]
        public Nullable<decimal> duration { get; set; }

        [Display(Name = "Fee")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> fee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrolled> Enrolleds { get; set; }
    }
}
