//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiLearn_JeffreyOdogba.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Enrolled
    {
        public int EnrollmentId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> CourseId { get; set; }

        [Display(Name = "Status")]
        public string Request { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Member Member { get; set; }
    }
}
